# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo-lab
  labels:
    app: todo-backend
    env: dev
data:
  MONGO_CONN_STR: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-svc:27017/todo?authSource=admin"
  USE_DB_AUTH: "false"
  PORT: "8080"
