# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: todo-lab
  labels:
    app: todo-backend
    env: dev
spec:
  selector:
    app: todo-backend
  ports:
  - port: 8080
    targetPort: backend-port
    protocol: TCP
