# MongoDB Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: dev
  labels:
    app: mongo-db
spec:
  clusterIP: None
  selector:
    app: mongo-db
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
